### ISSUE TITLE
Invalid hook call.

### ISSUE THREAD

**Issue by cawfree** [interhub/react-native-accelerometer-parallax#1]
Thanks for sharing this awesome project! It looks really great.

I tried to install but it looks like because things like `react` and `react-native` are specified as `dependencies` in the `package.json`, this package installs a duplicate copy of `react` in it's own `node_modules` directory, which causes the rules of hooks to be broken.

I believe this could be fixed by moving the dependencies specified into `devDependencies`.

![image](https://user-images.githubusercontent.com/7922333/118225118-592d0880-b47c-11eb-9146-46ee58162104.png)

**Comment by interhub** [comment]
> Thanks for sharing this awesome project! It looks really great.
> 
> I tried to install but it looks like because things like `react` and `react-native` are specified as `dependencies` in the `package.json`, this package installs a duplicate copy of `react` in it's own `node_modules` directory, which causes the rules of hooks to be broken.
> 
> I believe this could be fixed by moving the dependencies specified into `devDependencies`.
> 
> ![image](https://user-images.githubusercontent.com/7922333/118225118-592d0880-b47c-11eb-9146-46ee58162104.png)

Thanks today i going to fix it🤝

**Comment by interhub** [comment]
It was Fixed now, thanks you ✨❤️✅
version 1.5.0

**Comment by cawfree** [comment]
Cheers @interhub, can't wait to check it out. 💪
